theme: minima
permalink: /:year/:month/:day/:title
baseurl: '/'
url: 'https://zenkarsha.github.io/blog'

title: blog
description: 日常雜記，偶爾寫些coding心得
navigation:
  - title: biography
    url: https://zenkarsha.github.io/biography/
  - title: poetry
    url: https://zenkarsha.github.io/poetry/
  - title: muse
    url: https://zenkarsha.github.io/muse/
  - title: whisper
    url: https://zenkarsha.github.io/whisper/
  - title: favorite
    url: https://zenkarsha.github.io/favorite/
  - title: works
    url: https://zenkarsha.github.io/works/
  - title: twitter
    url: https://twitter.com/zenkarsha/

plugins:
  - jekyll-feed
